<?xml version="1.0" encoding="utf-8"?><Database Name="xw" Class="NDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=47.94.250.146;Initial Catalog=xw;User ID=xw" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="xwConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.N_Category" Member="N_Category">
    <Type Name="N_Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="enName" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="chName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="rank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.N_Description" Member="N_Description">
    <Type Name="N_Description">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="descriptionType" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="skuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="exAttr" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.N_Option" Member="N_Option">
    <Type Name="N_Option">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optionName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="optionValues" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="skuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isMain" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.N_OptionImage" Member="N_OptionImage">
    <Type Name="N_OptionImage">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="optionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="picBigUrl" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="isDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.N_OptionOther" Member="N_OptionOther">
    <Type Name="N_OptionOther">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="optionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="buyPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sSkuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dSkuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.N_Product" Member="N_Product">
    <Type Name="N_Product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="maxPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="minPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="storeCoverPic" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="storeCoverDesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="storeCoverPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="state" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.N_Sku" Member="N_Sku">
    <Type Name="N_Sku">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="skuNumber" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="fulfillmentType" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="isDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="salePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="retailPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="pId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>