#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace N_Admin.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="xw")]
	public partial class NDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertN_Category(N_Category instance);
    partial void UpdateN_Category(N_Category instance);
    partial void DeleteN_Category(N_Category instance);
    partial void InsertN_Description(N_Description instance);
    partial void UpdateN_Description(N_Description instance);
    partial void DeleteN_Description(N_Description instance);
    partial void InsertN_Option(N_Option instance);
    partial void UpdateN_Option(N_Option instance);
    partial void DeleteN_Option(N_Option instance);
    partial void InsertN_OptionImage(N_OptionImage instance);
    partial void UpdateN_OptionImage(N_OptionImage instance);
    partial void DeleteN_OptionImage(N_OptionImage instance);
    partial void InsertN_OptionOther(N_OptionOther instance);
    partial void UpdateN_OptionOther(N_OptionOther instance);
    partial void DeleteN_OptionOther(N_OptionOther instance);
    partial void InsertN_Product(N_Product instance);
    partial void UpdateN_Product(N_Product instance);
    partial void DeleteN_Product(N_Product instance);
    partial void InsertN_Sku(N_Sku instance);
    partial void UpdateN_Sku(N_Sku instance);
    partial void DeleteN_Sku(N_Sku instance);
    #endregion
		
		public NDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["xwConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<N_Category> N_Category
		{
			get
			{
				return this.GetTable<N_Category>();
			}
		}
		
		public System.Data.Linq.Table<N_Description> N_Description
		{
			get
			{
				return this.GetTable<N_Description>();
			}
		}
		
		public System.Data.Linq.Table<N_Option> N_Option
		{
			get
			{
				return this.GetTable<N_Option>();
			}
		}
		
		public System.Data.Linq.Table<N_OptionImage> N_OptionImage
		{
			get
			{
				return this.GetTable<N_OptionImage>();
			}
		}
		
		public System.Data.Linq.Table<N_OptionOther> N_OptionOther
		{
			get
			{
				return this.GetTable<N_OptionOther>();
			}
		}
		
		public System.Data.Linq.Table<N_Product> N_Product
		{
			get
			{
				return this.GetTable<N_Product>();
			}
		}
		
		public System.Data.Linq.Table<N_Sku> N_Sku
		{
			get
			{
				return this.GetTable<N_Sku>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.N_Category")]
	public partial class N_Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _enName;
		
		private string _chName;
		
		private int _rank;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnenNameChanging(string value);
    partial void OnenNameChanged();
    partial void OnchNameChanging(string value);
    partial void OnchNameChanged();
    partial void OnrankChanging(int value);
    partial void OnrankChanged();
    #endregion
		
		public N_Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enName", DbType="VarChar(80)")]
		public string enName
		{
			get
			{
				return this._enName;
			}
			set
			{
				if ((this._enName != value))
				{
					this.OnenNameChanging(value);
					this.SendPropertyChanging();
					this._enName = value;
					this.SendPropertyChanged("enName");
					this.OnenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chName", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string chName
		{
			get
			{
				return this._chName;
			}
			set
			{
				if ((this._chName != value))
				{
					this.OnchNameChanging(value);
					this.SendPropertyChanging();
					this._chName = value;
					this.SendPropertyChanged("chName");
					this.OnchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rank", DbType="Int NOT NULL")]
		public int rank
		{
			get
			{
				return this._rank;
			}
			set
			{
				if ((this._rank != value))
				{
					this.OnrankChanging(value);
					this.SendPropertyChanging();
					this._rank = value;
					this.SendPropertyChanged("rank");
					this.OnrankChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.N_Description")]
	public partial class N_Description : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _descriptionType;
		
		private string _description;
		
		private byte _type;
		
		private int _pId;
		
		private string _exAttr;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionTypeChanging(string value);
    partial void OndescriptionTypeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OntypeChanging(byte value);
    partial void OntypeChanged();
    partial void OnskuIdChanging(int value);
    partial void OnskuIdChanged();
    partial void OnexAttrChanging(string value);
    partial void OnexAttrChanged();
    #endregion
		
		public N_Description()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptionType", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string descriptionType
		{
			get
			{
				return this._descriptionType;
			}
			set
			{
				if ((this._descriptionType != value))
				{
					this.OndescriptionTypeChanging(value);
					this.SendPropertyChanging();
					this._descriptionType = value;
					this.SendPropertyChanged("descriptionType");
					this.OndescriptionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="TinyInt NOT NULL")]
		public byte type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pId", DbType="Int NOT NULL")]
		public int pId
		{
			get
			{
				return this._pId;
			}
			set
			{
				if ((this._pId != value))
				{
					this.OnskuIdChanging(value);
					this.SendPropertyChanging();
					this._pId = value;
					this.SendPropertyChanged("pId");
					this.OnskuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exAttr", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string exAttr
		{
			get
			{
				return this._exAttr;
			}
			set
			{
				if ((this._exAttr != value))
				{
					this.OnexAttrChanging(value);
					this.SendPropertyChanging();
					this._exAttr = value;
					this.SendPropertyChanged("exAttr");
					this.OnexAttrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.N_Option")]
	public partial class N_Option : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _optionName;
		
		private string _optionValues;
		
		private int _skuId;
		
		private bool _isMain;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnoptionNameChanging(string value);
    partial void OnoptionNameChanged();
    partial void OnoptionValuesChanging(string value);
    partial void OnoptionValuesChanged();
    partial void OnskuIdChanging(int value);
    partial void OnskuIdChanged();
    partial void OnisMainChanging(bool value);
    partial void OnisMainChanged();
    #endregion
		
		public N_Option()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionName", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string optionName
		{
			get
			{
				return this._optionName;
			}
			set
			{
				if ((this._optionName != value))
				{
					this.OnoptionNameChanging(value);
					this.SendPropertyChanging();
					this._optionName = value;
					this.SendPropertyChanged("optionName");
					this.OnoptionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionValues", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string optionValues
		{
			get
			{
				return this._optionValues;
			}
			set
			{
				if ((this._optionValues != value))
				{
					this.OnoptionValuesChanging(value);
					this.SendPropertyChanging();
					this._optionValues = value;
					this.SendPropertyChanged("optionValues");
					this.OnoptionValuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skuId", DbType="Int NOT NULL")]
		public int skuId
		{
			get
			{
				return this._skuId;
			}
			set
			{
				if ((this._skuId != value))
				{
					this.OnskuIdChanging(value);
					this.SendPropertyChanging();
					this._skuId = value;
					this.SendPropertyChanged("skuId");
					this.OnskuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isMain", DbType="Bit NOT NULL")]
		public bool isMain
		{
			get
			{
				return this._isMain;
			}
			set
			{
				if ((this._isMain != value))
				{
					this.OnisMainChanging(value);
					this.SendPropertyChanging();
					this._isMain = value;
					this.SendPropertyChanged("isMain");
					this.OnisMainChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.N_OptionImage")]
	public partial class N_OptionImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _optionId;
		
		private string _picBigUrl;
		
		private bool _isDefault;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnoptionIdChanging(int value);
    partial void OnoptionIdChanged();
    partial void OnpicBigUrlChanging(string value);
    partial void OnpicBigUrlChanged();
    partial void OnisDefaultChanging(bool value);
    partial void OnisDefaultChanged();
    #endregion
		
		public N_OptionImage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionId", DbType="Int NOT NULL")]
		public int optionId
		{
			get
			{
				return this._optionId;
			}
			set
			{
				if ((this._optionId != value))
				{
					this.OnoptionIdChanging(value);
					this.SendPropertyChanging();
					this._optionId = value;
					this.SendPropertyChanged("optionId");
					this.OnoptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picBigUrl", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string picBigUrl
		{
			get
			{
				return this._picBigUrl;
			}
			set
			{
				if ((this._picBigUrl != value))
				{
					this.OnpicBigUrlChanging(value);
					this.SendPropertyChanging();
					this._picBigUrl = value;
					this.SendPropertyChanged("picBigUrl");
					this.OnpicBigUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDefault", DbType="Bit NOT NULL")]
		public bool isDefault
		{
			get
			{
				return this._isDefault;
			}
			set
			{
				if ((this._isDefault != value))
				{
					this.OnisDefaultChanging(value);
					this.SendPropertyChanging();
					this._isDefault = value;
					this.SendPropertyChanged("isDefault");
					this.OnisDefaultChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.N_OptionOther")]
	public partial class N_OptionOther : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _optionId;
		
		private int _buyPrice;
		
		private int _sSkuId;
		
		private int _dSkuId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnoptionIdChanging(int value);
    partial void OnoptionIdChanged();
    partial void OnbuyPriceChanging(int value);
    partial void OnbuyPriceChanged();
    partial void OnsSkuIdChanging(int value);
    partial void OnsSkuIdChanged();
    partial void OndSkuIdChanging(int value);
    partial void OndSkuIdChanged();
    #endregion
		
		public N_OptionOther()
		{
			OnCreated();
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionId", DbType="Int NOT NULL")]
		public int optionId
		{
			get
			{
				return this._optionId;
			}
			set
			{
				if ((this._optionId != value))
				{
					this.OnoptionIdChanging(value);
					this.SendPropertyChanging();
					this._optionId = value;
					this.SendPropertyChanged("optionId");
					this.OnoptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buyPrice", DbType="Int NOT NULL")]
		public int buyPrice
		{
			get
			{
				return this._buyPrice;
			}
			set
			{
				if ((this._buyPrice != value))
				{
					this.OnbuyPriceChanging(value);
					this.SendPropertyChanging();
					this._buyPrice = value;
					this.SendPropertyChanged("buyPrice");
					this.OnbuyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSkuId", DbType="Int NOT NULL")]
		public int sSkuId
		{
			get
			{
				return this._sSkuId;
			}
			set
			{
				if ((this._sSkuId != value))
				{
					this.OnsSkuIdChanging(value);
					this.SendPropertyChanging();
					this._sSkuId = value;
					this.SendPropertyChanged("sSkuId");
					this.OnsSkuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dSkuId", DbType="Int NOT NULL")]
		public int dSkuId
		{
			get
			{
				return this._dSkuId;
			}
			set
			{
				if ((this._dSkuId != value))
				{
					this.OndSkuIdChanging(value);
					this.SendPropertyChanging();
					this._dSkuId = value;
					this.SendPropertyChanged("dSkuId");
					this.OndSkuIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.N_Product")]
	public partial class N_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private int _maxPrice;
		
		private int _minPrice;
		
		private int _cid;
		
		private string _storeCoverPic;
		
		private string _storeCoverDesc;
		
		private int _storeCoverPrice;
		
		private System.Nullable<int> _count;
		
		private System.Nullable<bool> _state;
		
		private System.DateTime _createDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmaxPriceChanging(int value);
    partial void OnmaxPriceChanged();
    partial void OnminPriceChanging(int value);
    partial void OnminPriceChanged();
    partial void OncidChanging(int value);
    partial void OncidChanged();
    partial void OnstoreCoverPicChanging(string value);
    partial void OnstoreCoverPicChanged();
    partial void OnstoreCoverDescChanging(string value);
    partial void OnstoreCoverDescChanged();
    partial void OnstoreCoverPriceChanging(int value);
    partial void OnstoreCoverPriceChanged();
    partial void OncountChanging(System.Nullable<int> value);
    partial void OncountChanged();
    partial void OnstateChanging(System.Nullable<bool> value);
    partial void OnstateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    #endregion
		
		public N_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxPrice", DbType="Int NOT NULL")]
		public int maxPrice
		{
			get
			{
				return this._maxPrice;
			}
			set
			{
				if ((this._maxPrice != value))
				{
					this.OnmaxPriceChanging(value);
					this.SendPropertyChanging();
					this._maxPrice = value;
					this.SendPropertyChanged("maxPrice");
					this.OnmaxPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minPrice", DbType="Int NOT NULL")]
		public int minPrice
		{
			get
			{
				return this._minPrice;
			}
			set
			{
				if ((this._minPrice != value))
				{
					this.OnminPriceChanging(value);
					this.SendPropertyChanging();
					this._minPrice = value;
					this.SendPropertyChanged("minPrice");
					this.OnminPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="Int NOT NULL")]
		public int cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					this.OncidChanging(value);
					this.SendPropertyChanging();
					this._cid = value;
					this.SendPropertyChanged("cid");
					this.OncidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storeCoverPic", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string storeCoverPic
		{
			get
			{
				return this._storeCoverPic;
			}
			set
			{
				if ((this._storeCoverPic != value))
				{
					this.OnstoreCoverPicChanging(value);
					this.SendPropertyChanging();
					this._storeCoverPic = value;
					this.SendPropertyChanged("storeCoverPic");
					this.OnstoreCoverPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storeCoverDesc", DbType="VarChar(255)")]
		public string storeCoverDesc
		{
			get
			{
				return this._storeCoverDesc;
			}
			set
			{
				if ((this._storeCoverDesc != value))
				{
					this.OnstoreCoverDescChanging(value);
					this.SendPropertyChanging();
					this._storeCoverDesc = value;
					this.SendPropertyChanged("storeCoverDesc");
					this.OnstoreCoverDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storeCoverPrice", DbType="Int NOT NULL")]
		public int storeCoverPrice
		{
			get
			{
				return this._storeCoverPrice;
			}
			set
			{
				if ((this._storeCoverPrice != value))
				{
					this.OnstoreCoverPriceChanging(value);
					this.SendPropertyChanging();
					this._storeCoverPrice = value;
					this.SendPropertyChanged("storeCoverPrice");
					this.OnstoreCoverPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int")]
		public System.Nullable<int> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this.OncountChanging(value);
					this.SendPropertyChanging();
					this._count = value;
					this.SendPropertyChanged("count");
					this.OncountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Bit")]
		public System.Nullable<bool> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.N_Sku")]
	public partial class N_Sku : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _quantity;
		
		private string _skuNumber;
		
		private string _fulfillmentType;
		
		private bool _isDefault;
		
		private int _salePrice;
		
		private int _retailPrice;
		
		private string _name;
		
		private bool _state;
		
		private System.DateTime _createDate;
		
		private System.Nullable<int> _pId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OnskuNumberChanging(string value);
    partial void OnskuNumberChanged();
    partial void OnfulfillmentTypeChanging(string value);
    partial void OnfulfillmentTypeChanged();
    partial void OnisDefaultChanging(bool value);
    partial void OnisDefaultChanged();
    partial void OnsalePriceChanging(int value);
    partial void OnsalePriceChanged();
    partial void OnretailPriceChanging(int value);
    partial void OnretailPriceChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstateChanging(bool value);
    partial void OnstateChanged();
    partial void OncreateDateChanging(System.DateTime value);
    partial void OncreateDateChanged();
    partial void OnpIdChanging(System.Nullable<int> value);
    partial void OnpIdChanged();
    #endregion
		
		public N_Sku()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skuNumber", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string skuNumber
		{
			get
			{
				return this._skuNumber;
			}
			set
			{
				if ((this._skuNumber != value))
				{
					this.OnskuNumberChanging(value);
					this.SendPropertyChanging();
					this._skuNumber = value;
					this.SendPropertyChanged("skuNumber");
					this.OnskuNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fulfillmentType", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string fulfillmentType
		{
			get
			{
				return this._fulfillmentType;
			}
			set
			{
				if ((this._fulfillmentType != value))
				{
					this.OnfulfillmentTypeChanging(value);
					this.SendPropertyChanging();
					this._fulfillmentType = value;
					this.SendPropertyChanged("fulfillmentType");
					this.OnfulfillmentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDefault", DbType="Bit NOT NULL")]
		public bool isDefault
		{
			get
			{
				return this._isDefault;
			}
			set
			{
				if ((this._isDefault != value))
				{
					this.OnisDefaultChanging(value);
					this.SendPropertyChanging();
					this._isDefault = value;
					this.SendPropertyChanged("isDefault");
					this.OnisDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salePrice", DbType="Int NOT NULL")]
		public int salePrice
		{
			get
			{
				return this._salePrice;
			}
			set
			{
				if ((this._salePrice != value))
				{
					this.OnsalePriceChanging(value);
					this.SendPropertyChanging();
					this._salePrice = value;
					this.SendPropertyChanged("salePrice");
					this.OnsalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_retailPrice", DbType="Int NOT NULL")]
		public int retailPrice
		{
			get
			{
				return this._retailPrice;
			}
			set
			{
				if ((this._retailPrice != value))
				{
					this.OnretailPriceChanging(value);
					this.SendPropertyChanging();
					this._retailPrice = value;
					this.SendPropertyChanged("retailPrice");
					this.OnretailPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Bit NOT NULL")]
		public bool state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createDate", DbType="DateTime NOT NULL")]
		public System.DateTime createDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				if ((this._createDate != value))
				{
					this.OncreateDateChanging(value);
					this.SendPropertyChanging();
					this._createDate = value;
					this.SendPropertyChanged("createDate");
					this.OncreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pId", DbType="Int")]
		public System.Nullable<int> pId
		{
			get
			{
				return this._pId;
			}
			set
			{
				if ((this._pId != value))
				{
					this.OnpIdChanging(value);
					this.SendPropertyChanging();
					this._pId = value;
					this.SendPropertyChanged("pId");
					this.OnpIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
