#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace N_Admin.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="xw")]
	public partial class SDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertS_Authstore(S_Authstore instance);
    partial void UpdateS_Authstore(S_Authstore instance);
    partial void DeleteS_Authstore(S_Authstore instance);
    #endregion
		
		public SDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["xwConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<S_Authstore> S_Authstore
		{
			get
			{
				return this.GetTable<S_Authstore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.S_Authstore")]
	public partial class S_Authstore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _asAddr;
		
		private string _businessHours;
		
		private string _tel1;
		
		private string _tel2;
		
		private string _email;
		
		private string _ownerName;
		
		private string _businesserName;
		
		private string _storeName;
		
		private string _introImg;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnasAddrChanging(string value);
    partial void OnasAddrChanged();
    partial void OnbusinessHoursChanging(string value);
    partial void OnbusinessHoursChanged();
    partial void Ontel1Changing(string value);
    partial void Ontel1Changed();
    partial void Ontel2Changing(string value);
    partial void Ontel2Changed();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnownerNameChanging(string value);
    partial void OnownerNameChanged();
    partial void OnbusinesserNameChanging(string value);
    partial void OnbusinesserNameChanged();
    partial void OnstoreNameChanging(string value);
    partial void OnstoreNameChanged();
    partial void OnintroImgChanging(string value);
    partial void OnintroImgChanged();
    #endregion
		
		public S_Authstore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asAddr", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string asAddr
		{
			get
			{
				return this._asAddr;
			}
			set
			{
				if ((this._asAddr != value))
				{
					this.OnasAddrChanging(value);
					this.SendPropertyChanging();
					this._asAddr = value;
					this.SendPropertyChanged("asAddr");
					this.OnasAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_businessHours", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string businessHours
		{
			get
			{
				return this._businessHours;
			}
			set
			{
				if ((this._businessHours != value))
				{
					this.OnbusinessHoursChanging(value);
					this.SendPropertyChanging();
					this._businessHours = value;
					this.SendPropertyChanged("businessHours");
					this.OnbusinessHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel1", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string tel1
		{
			get
			{
				return this._tel1;
			}
			set
			{
				if ((this._tel1 != value))
				{
					this.Ontel1Changing(value);
					this.SendPropertyChanging();
					this._tel1 = value;
					this.SendPropertyChanged("tel1");
					this.Ontel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel2", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string tel2
		{
			get
			{
				return this._tel2;
			}
			set
			{
				if ((this._tel2 != value))
				{
					this.Ontel2Changing(value);
					this.SendPropertyChanging();
					this._tel2 = value;
					this.SendPropertyChanged("tel2");
					this.Ontel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerName", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string ownerName
		{
			get
			{
				return this._ownerName;
			}
			set
			{
				if ((this._ownerName != value))
				{
					this.OnownerNameChanging(value);
					this.SendPropertyChanging();
					this._ownerName = value;
					this.SendPropertyChanged("ownerName");
					this.OnownerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_businesserName", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string businesserName
		{
			get
			{
				return this._businesserName;
			}
			set
			{
				if ((this._businesserName != value))
				{
					this.OnbusinesserNameChanging(value);
					this.SendPropertyChanging();
					this._businesserName = value;
					this.SendPropertyChanged("businesserName");
					this.OnbusinesserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storeName", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string storeName
		{
			get
			{
				return this._storeName;
			}
			set
			{
				if ((this._storeName != value))
				{
					this.OnstoreNameChanging(value);
					this.SendPropertyChanging();
					this._storeName = value;
					this.SendPropertyChanged("storeName");
					this.OnstoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_introImg", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string introImg
		{
			get
			{
				return this._introImg;
			}
			set
			{
				if ((this._introImg != value))
				{
					this.OnintroImgChanging(value);
					this.SendPropertyChanging();
					this._introImg = value;
					this.SendPropertyChanged("introImg");
					this.OnintroImgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
