<?xml version="1.0" encoding="utf-8"?><Database Name="xw" Class="UDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=47.94.250.146;Initial Catalog=xw;User ID=xw" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="xwConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.U_User" Member="U_User">
    <Type Name="U_User">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>